name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16, 12.4]
        test-repo: ["facebook/react"]
        lint-options: ["-p 4 --parallel-files 20", "-p 2 --parallel-files 20", ""]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: clone test repo
      run: |
        cd ..
        git clone https://github.com/${{ matrix.test-repo }}.git repo
        cd repo
        yarn
    - name: lint test repo
      run: |
        pwd
        ls
        T1=`date +%s`
        ../eslint/bin/eslint.js${{ matrix.lint-options }}--quiet .
        T2=`date +%s`
        echo $(($T2-T1))
        echo "linting time: $(($T2-T1))s"




