name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 600

    strategy:
      matrix:
        test-repo:
        - "webpack/webpack" # 796 files to lint
        - "facebook/react" # 1011 files to lint
        # - "eslint/eslint" # 721 files to lint
        - "nodejs/node" # 744 files
        # - "zeit/next.js" # no eslint config
        # - "mrdoob/three.js" # 1388 files, out of memory
        repeat: [1, 2, 3, 4]
        node-version: [10.16]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install --production
    - name: clone test repo
      run: |
        cd ..
        git clone --depth 1 https://github.com/${{ matrix.test-repo }}.git repo
        cd repo
        yarn
        if [[ ${{ matrix.test-repo }} == *"node"* ]]; then
          echo "test" >> .eslintignore
          echo "deps/v8/tools/profviz/gnuplot-4.6.3-emscripten.js" >> .eslintignore
        fi
        cat .eslintignore
    # - name: lint sync [warm up]
    #   shell: bash {0}
    #   env:
    #     DEBUG: eslint:cli-engine:perf
    #   run: |
    #     echo "# of cores `nproc --all`"
    #     cd ../repo
    #     echo "starting run"
    #     T1=`date +%s`
    #     ../eslint/bin/eslint.js .
    #     T2=`date +%s`
    #     echo "linting time: $(($T2-T1))s"
    - name: lint parallel
      shell: bash {0}
      env:
        DEBUG: eslint:cli-engine:perf
      run: |
        echo "# of cores `nproc --all`"
        cd ../repo
        echo "starting run"
        T1=`date +%s`
        ../eslint/bin/eslint.js -p .
        T2=`date +%s`
        echo "linting time: $(($T2-T1))s"
    - name: lint parallel
      shell: bash {0}
      env:
        DEBUG: eslint:cli-engine:perf
      run: |
        echo "# of cores `nproc --all`"
        cd ../repo
        echo "starting run"
        T1=`date +%s`
        ../eslint/bin/eslint.js -p .
        T2=`date +%s`
        echo "linting time: $(($T2-T1))s"
    - name: lint sync
      shell: bash {0}
      env:
        DEBUG: eslint:cli-engine:perf
      run: |
        echo "# of cores `nproc --all`"
        cd ../repo
        echo "starting run"
        T1=`date +%s`
        ../eslint/bin/eslint.js .
        T2=`date +%s`
        echo "linting time: $(($T2-T1))s"
