name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 600

    strategy:
      matrix:
        repeat: [1, 2, 3]
        lint-options: ["-p 4 --parallel-files 30", "-p 2 --parallel-files 30", ""]
        test-repo: ["facebook/react"]
        node-version: [10.16]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: clone test repo
      run: |
        cd ..
        git clone https://github.com/${{ matrix.test-repo }}.git repo
        cd repo
        yarn
    - name: lint test repo
      shell: bash {0}
      run: |
        cd ../repo
        echo "starting run #${{ matrix.repeat }}"
        T1=`date +%s`
        ../eslint/bin/eslint.js ${{ matrix.lint-options }} --quiet .
        T2=`date +%s`
        echo $(($T2-T1))
        echo "linting time: $(($T2-T1))s"




