name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 600

    strategy:
      matrix:
        repeat: [1, 2, 3, 4, 5]

        test-repo:
        - "webpack/webpack" # => 796 files to lint
        - "facebook/react"
        # - "nodejs/node"
        - "eslint/eslint"
        # - "zeit/next.js"
        # - "mrdoob/three.js"
        node-version: [10.16]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install --production
    - name: clone test repo
      run: |
        cd ..
        git clone --depth 1 https://github.com/${{ matrix.test-repo }}.git repo
        cd repo
        yarn
    - name: lint sync [warm up]
      shell: bash {0}
      env:
        DEBUG: eslint:cli-engine:perf
      run: |
        echo "# of cores `nproc --all`"
        cd ../repo
        echo "starting run"
        T1=`date +%s`
        ../eslint/bin/eslint.js .
        T2=`date +%s`
        echo "linting time: $(($T2-T1))s"
    - name: lint parallel
      shell: bash {0}
      env:
        DEBUG: eslint:cli-engine:perf
      run: |
        echo "# of cores `nproc --all`"
        cd ../repo
        echo "starting run"
        T1=`date +%s`
        ../eslint/bin/eslint.js -p 2 --parallel-files 30 .
        T2=`date +%s`
        echo "linting time: $(($T2-T1))s"
    - name: lint sync
      shell: bash {0}
      env:
        DEBUG: eslint:cli-engine:perf
      run: |
        echo "# of cores `nproc --all`"
        cd ../repo
        echo "starting run"
        T1=`date +%s`
        ../eslint/bin/eslint.js .
        T2=`date +%s`
        echo "linting time: $(($T2-T1))s"
