name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16, 12.4]
        test-repo: ["facebook/react"]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: clone test repo
      run: |
        cd ..
        git clone https://github.com/${{ matrix.test-repo }}.git repo
        cd repo
        yarn
        ../eslint/bin/eslint.js -p 4 --parallel-files 20  --quiet .
      env:
        CI: true
